modLoader="kotlinforforge"
loaderVersion="[3,)"
license="All rights reserved"
issueTrackerURL="https://github.com/eifelmine/bionisation4/issues"
[[mods]]
modId="bionisation4"
version="1.0.0.2"
displayName="Bionisation 4"
displayURL="https://github.com/eifelmine/bionisation4"
logoFile="examplemod.png"
credits="Eifel"
authors="Eifel"
description='''
Bionisation 4 is a mod about viruses and bacteria in Minecraft.
'''

